//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoExam
{
    using System;
    using System.Collections.Generic;
    
    public partial class prod
    {
        public int id { get; set; }
        public string name { get; set; }
        public string data { get; set; }
        public Nullable<int> id_category { get; set; }
    }
}
